import { Stone } from "./types";

export const STONES_DATA: Stone[] = [
  {
    id: "calacatta_gold",
    name: "Calacatta Gold Premium",
    category: "marble",
    description: "O expoente máximo do luxo. Fundo branco puro com veios dramáticos cinza e sutis ramificações douradas.",
    origin: "Itália (Apuan Alps)",
    color: "Branco e Dourado",
    pattern: "Veios Dramáticos e Largos",
    durability: 5,
    stainResistance: 4,
    pricePerMeter: 3800,
    bgStyle: "linear-gradient(135deg, #ffffff 0%, #f9f9fb 40%, #ebd292 45%, #ffffff 50%, #dcdcdf 70%, #ffffff 100%)",
    textClass: "text-gray-950",
    isBestSeller: true
  },
  {
    id: "carrara_bianco",
    name: "Branco Carrara Gioia",
    category: "marble",
    description: "O eterno clássico da arquitetura mundial. Fundo branco cristalino com múltiplos veios suaves grafite.",
    origin: "Itália (Carrara)",
    color: "Branco Glacial",
    pattern: "Fino e Ramificado",
    durability: 6,
    stainResistance: 4,
    pricePerMeter: 1950,
    bgStyle: "radial-gradient(circle at 30% 20%, #ffffff 0%, #efeff2 50%, #cccccc 52%, #f5f5f7 55%, #eaeaea 80%)",
    textClass: "text-gray-950"
  },
  {
    id: "nero_marquina",
    name: "Nero Marquina",
    category: "marble",
    description: "Contraste absoluto e teatral. Fundo preto carvão profundo com fósseis e veios brancos cristalinos marcantes.",
    origin: "Espanha (Basque Country)",
    color: "Preto Absoluto",
    pattern: "Veios Brancos Geométricos",
    durability: 6,
    stainResistance: 5,
    pricePerMeter: 2100,
    bgStyle: "linear-gradient(145deg, #09090b 0%, #17171f 30%, #fcfcfc 33%, #17171f 36%, #0d0d12 70%, #ffffff 71%, #09090b 74%, #18181b 100%)",
    textClass: "text-white"
  },
  {
    id: "verde_alpi",
    name: "Verde Alpi Imperial",
    category: "marble",
    description: "Arrojado e aristocrático. Tom de verde-floresta escuro com intensos veios esmeralda e listras calcárias claras.",
    origin: "Itália (Val d'Aosta)",
    color: "Verde Escuro / Esmeralda",
    pattern: "Estriado e Intrincado",
    durability: 7,
    stainResistance: 5,
    pricePerMeter: 2400,
    bgStyle: "linear-gradient(125deg, #062f22 0%, #0c3a2b 30%, #52b788 34%, #0c3a2b 38%, #031c14 70%, #ffffff 72%, #031c14 75%, #0c3a2b 100%)",
    textClass: "text-white"
  },
  {
    id: "taj_mahal",
    name: "Quartzito Taj Mahal Noble",
    category: "quartzite",
    description: "A joia dos quartzitos nacionais, assemelha-se ao mármore porém com dureza superior à do próprio granito.",
    origin: "Brasil (Ceará)",
    color: "Champagne / Marfim",
    pattern: "Nuvens e Veios Suaves",
    durability: 9,
    stainResistance: 8,
    pricePerMeter: 3400,
    bgStyle: "linear-gradient(135deg, #eae1cc 0%, #f4eee1 30%, #ded3b8 50%, #f8f5ed 70%, #e5dbc4 100%)",
    textClass: "text-gray-950",
    isBestSeller: true
  },
  {
    id: "mont_blanc",
    name: "Quartzito Mont Blanc",
    category: "quartzite",
    description: "Aparência de mármore Carrara com a indestrutibilidade do quartzo natural. Fundo off-white com veios quentes cinza.",
    origin: "Brasil (Bahia)",
    color: "Branco Cálido",
    pattern: "Linear e Diagonal",
    durability: 9,
    stainResistance: 8,
    pricePerMeter: 3600,
    bgStyle: "linear-gradient(110deg, #fafafa 0%, #eaeaea 40%, #b8b8b8 42%, #fafafa 45%, #eee 70%, #999 72%, #fafafa 75%)",
    textClass: "text-gray-950"
  },
  {
    id: "preto_absoluto",
    name: "Granito Preto Absoluto Premium",
    category: "granite",
    description: "Estética minimalista impecável. Grão ultra-fino quase imperceptível, resultando em uma superfície espelhada preta pura.",
    origin: "Índia",
    color: "Preto Sólido",
    pattern: "Homogêneo Escurecido",
    durability: 8,
    stainResistance: 9,
    pricePerMeter: 1250,
    bgStyle: "linear-gradient(135deg, #09090b 0%, #111116 50%, #030303 100%)",
    textClass: "text-white"
  },
  {
    id: "preto_gabriel",
    name: "Granito Preto São Gabriel",
    category: "granite",
    description: "O campeão nacional em custo-benefício. Grãos médios pretos brilhantes, excelente vedação natural e durabilidade extrema.",
    origin: "Brasil (Espírito Santo)",
    color: "Preto Salpicado",
    pattern: "Grulado Refinado",
    durability: 8,
    stainResistance: 8,
    pricePerMeter: 720,
    bgStyle: "radial-gradient(circle, #27272a 4px, #18181b 5px)",
    textClass: "text-white"
  },
  {
    id: "dekton_laurent",
    name: "Dekton Laurent (Ultra-compacto)",
    category: "sintetico",
    description: "Material tecnológico ultra-prensado. Réplica de mármore negro com veios ferrugem e dourados, à prova de calor direto e riscos.",
    origin: "Espanha (Cosentino)",
    color: "Negro com Veios Bronze",
    pattern: "Dramático Diagonal",
    durability: 10,
    stainResistance: 10,
    pricePerMeter: 4600,
    bgStyle: "linear-gradient(120deg, #18181b 0%, #1b1613 30%, #e28743 32%, #1b1613 34%, #18181b 60%, #e28743 62%, #18181b 100%)",
    textClass: "text-white",
    isBestSeller: true
  },
  {
    id: "quartzo_pure_white",
    name: "Quartzo Absolute Pure White",
    category: "sintetico",
    description: "94% quartzo natural puro e resina cirúrgica. Branco puríssimo e uniforme, ideal para uma estética limpa, reta e moderna.",
    origin: "Importado",
    color: "Branco Neve Puro",
    pattern: "Totalmente Uniforme",
    durability: 9,
    stainResistance: 9,
    pricePerMeter: 1100,
    bgStyle: "linear-gradient(135deg, #ffffff 0%, #f8fafc 100%)",
    textClass: "text-gray-950"
  }
];
